# github action to deploy invoice api to azure

name: Deploy Invoice Api

on:
  push:

env:
  AZURE_WEBAPP_NAME: "InvoiceappApi"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./InvoiceAppWebApi/InvoiceApp.Api.csproj

      - name: Build
        run: dotnet build ./InvoiceAppWebApi/InvoiceApp.Api.csproj --configuration Release --no-restore

      # publish
      - name: Publish
        run: dotnet publish ./InvoiceAppWebApi/InvoiceApp.Api.csproj --configuration Release --output ./publish

      # deploy to azure
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish
